// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Enum_Colors
{
	info(new String[][] { new String[] { "en_US", "info" } }),
	warning(new String[][] { new String[] { "en_US", "warning" } }),
	danger(new String[][] { new String[] { "en_US", "danger" } }),
	active(new String[][] { new String[] { "en_US", "active" } }),
	success(new String[][] { new String[] { "en_US", "success" } });

	private java.util.Map<String,String> captions;

	private Enum_Colors(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
